# Generated by Django 6.0.1 on 2026-01-17 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('on_hold', 'On hold'), ('complete', 'Complete')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('program_name', models.CharField(max_length=120)),
                ('phase', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('in_progress', 'In progress'), ('at_risk', 'At risk')], max_length=20)),
                ('percent_complete', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='MediaUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('update', 'Update'), ('camera_feed', 'Camera feed')], max_length=20)),
                ('media_url', models.URLField()),
                ('captured_at', models.DateTimeField()),
                ('uploaded_by', models.CharField(max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_updates', to='core.project')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('plan', 'Plan'), ('approval', 'Approval'), ('report', 'Report'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField()),
                ('version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], max_length=20)),
                ('uploaded_by', models.CharField(max_length=120)),
                ('uploaded_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('original_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approved_variations', models.DecimalField(decimal_places=2, max_digits=14)),
                ('forecast_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_spent', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('cost_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='core.project')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('requested_by', models.CharField(max_length=120)),
                ('requested_at', models.DateTimeField()),
                ('reviewed_by', models.CharField(blank=True, max_length=120, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.project')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('update', 'Update')], max_length=20)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rfi',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('rfi_number', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('closed', 'Closed')], max_length=20)),
                ('raised_by', models.CharField(max_length=120)),
                ('raised_at', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_summary', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='core.project')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=120)),
                ('likelihood', models.PositiveIntegerField()),
                ('impact', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigating', 'Mitigating'), ('closed', 'Closed')], max_length=20)),
                ('owner', models.CharField(max_length=120)),
                ('due_date', models.DateField()),
                ('mitigation_plan', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.project')),
            ],
            options={
                'ordering': ['-rating', 'title'],
            },
        ),
    ]
